### ISSUE TITLE
lvgl/lvgl.h: No such file or directory

### ISSUE THREAD

**Issue by andreacampanella** [lvgl/lv_port_linux_frame_buffer#11]
I was just trying to compile the latest release :

CC /home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/get_started/lv_example_get_started_3.c
CC /home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/get_started/lv_example_get_started_2.c
CC /home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/get_started/lv_example_get_started_1.c
/home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/assets/imgbtn_mid.c:4:10: fatal error: lvgl/lvgl.h: No such file or directory
 #include "lvgl/lvgl.h"
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:34: recipe for target '/home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/assets/imgbtn_mid.o' failed
make: *** [/home/andrea/gui/v8/lv_port_linux_frame_buffer/lvgl/examples/assets/imgbtn_mid.o] Error 1

**Comment by kisvegabor** [comment]
You need to add the parent folder of the `lvgl` directory as an include path. E.g. `-Imy_project/gui`
