### ISSUE TITLE
Segmentation fault when running demo app with rotation of LV_DISP_ROT_270

### ISSUE THREAD

**Issue by bigbearishappy** [lvgl/lv_port_linux_frame_buffer#13]
Hello.
I have make the lvgl demo work on my raspberrypi CM4 module.
When I rotate the app for 0 or 180 degrees.It works fine. But when I rotate it for 90 or 270 degrees.It break when I touch some place of the touch panel.
the log shows:"**Segmentation fault**"

I also have done some debug work for it.I find that when the error happens. **The log int drm_flush shows that the value of w is
negative.**

Is there anyway I can fix this error?
I will be appreciated if someone can help me out.

**Comment by bigbearishappy** [comment]
> I found the issue of incorrect cursor refresh. See here: [lvgl/lvgl@c514bdd](https://github.com/lvgl/lvgl/commit/c514bddd9b4064e2eba0c3ec4c7a51415acd74e4)
> 
> The `flushing_last` flag wasn't set therefore SDL didn't update the texture.
> 
> Probably it won't solve the issue of @bigbearishappy but let's give it a try :)

Cool, I'll try it next Monday.Thank you.

**Comment by bigbearishappy** [comment]
> I found the issue of incorrect cursor refresh. See here: [lvgl/lvgl@c514bdd](https://github.com/lvgl/lvgl/commit/c514bddd9b4064e2eba0c3ec4c7a51415acd74e4)
> 
> The `flushing_last` flag wasn't set therefore SDL didn't update the texture.
> 
> Probably it won't solve the issue of @bigbearishappy but let's give it a try :)

I have apply the patch and test on my machine. 
But the changes can not solve this issue.

**Comment by kisvegabor** [comment]
Can you debug the project to see how that weird area is calculated?

**Comment by bigbearishappy** [comment]
> Can you debug the project to see how that weird area is calculated?

OK,I'll have a try and reply to you.
