### ISSUE TITLE
 frame buffer of Ubuntu virtual machine question

### ISSUE THREAD

**Issue by shengzhe8688** [lvgl/lv_port_linux_frame_buffer#19]
The frame buffer of Ubuntu virtual machine is the same picture instead of a program that can be operated by mouse. Why

**Comment by embeddedt** [comment]
I'm not 100% sure what you mean, but it sounds like you're looking for a version that opens as a normal window. In that case, you're probably looking for the normal [PC simulator](https://github.com/lvgl/lv_sim_eclipse_sdl) project instead. This project is intended to be used in cases where there is no existing graphical environment (e.g. on the target platform).

**Comment by shengzhe8688** [comment]
<img width="1007" alt="微信截图_20220127123525" src="https://user-images.githubusercontent.com/16428236/151293703-50b56e84-c560-4f51-a4f9-3d5ffccb7591.png">
![image](https://user-images.githubusercontent.com/16428236/151293972-727f7c19-767e-4cf2-ac40-ab1a0055a774.png)


lv_port_linux_frame_buffer   can help me realize that in the virtual machine command mode, the mouse, keyboard and touch screen can be operated, and the command line cannot be input into the virtual machine interface (because the interface will be spent when the command line is input？

**Comment by shengzhe8688** [comment]
<img width="972" alt="微信截图_20220127125039" src="https://user-images.githubusercontent.com/16428236/151294041-69e362a6-6726-423d-9a21-df47b4b6a8c0.png">
Effect of interface spending

**Comment by kisvegabor** [comment]
As it's not related to LVGL itself, but a general Linux question I close this issue.

I suggest opening a topic in LVGL's Forum.
