### ISSUE TITLE
how do i run this repo

### ISSUE THREAD

**Issue by qNnOtTk** [lvgl/lv_port_linux_frame_buffer#21]
i wanna run littlevgl on /dev/fb1 but i have no idea where to start 
also, the tutorial isnt helpful at all, its 4 years old

**Comment by qNnOtTk** [comment]
i compiled it, running ./demo gives me this error
```
rock@radxa-zero:~/lv_port_linux_frame_buffer$ sudo ./demo
ioctl(FBIOBLANK): Invalid argument
unable to open evdev interface:: No such file or directory
```

**Comment by kisvegabor** [comment]
I also wanted to suggested to remove the `FBIOBLANK` line. :slightly_smiling_face: 

Please send a screen shot.

**Comment by embexus** [comment]
@qNnOtTk you can't just run it on your host ! it's probably running X11 or Wyland, try it on a target with framebuffer

**Comment by symfund** [comment]
To run this repo, your linux kernel must support frame buffer driver or DRM/KMS driver with legacy fbdev support. Also this repo can run in Wayland environment with or without X11!

**Comment by symfund** [comment]
![lvgl-wayland-calendar](https://user-images.githubusercontent.com/1295065/209455620-287ffd3e-809b-4b61-bbc8-7d9776bd3e2f.png)

**Comment by qNnOtTk** [comment]
Hi sorry i forgot about this issue i made, anyway, i figured out how to run it on X11, i just hid the cursor and ran it on fullscreen and its good enough for me, thanks for the help
