### ISSUE TITLE
Using 3rd-party lib qr-code shows "undefined reference"-error

### ISSUE THREAD

**Issue by ChrisPasda** [lvgl/lv_port_linux_frame_buffer#28]
I am trying to use the qr-code feature with this template for the fb0 in c and i activated this feature in the lv_conf.h. When i am using some qr-related functions like lv_qrcode_create() i get an "undefined reference"-error while compiling with make.  When i am clicking on the function my IDE finds the correct file in src/libs/qrcode.

Thank you very much in advance and with best regards,

Chris

**Comment by kisvegabor** [comment]
Do you build the project with Eclipse or Make?

**Comment by ChrisPasda** [comment]
Hey, i compiled with make.

Thanks for the response.

**Comment by kisvegabor** [comment]
I've checked that the make file [includes all C files](https://github.com/lvgl/lvgl/blob/49c59f4615857759cc8caf88424324ab6386c888/src/extra/lv_extra.mk) from the `extra`directory.

Please modify `lv_qrcode.c` like
```c
#error "before #if"
#include "lv_qrcode.h"
#if LV_USE_QRCODE
#error "after #if"
```

It will show if the file is being compiled or not.

**Comment by ChrisPasda** [comment]
I did that and that was my outcome:
![image](https://user-images.githubusercontent.com/48090514/195569542-02eda33e-1d9f-4f72-a98f-446e39567505.png)

Thank you very much for the response and best regards

**Comment by ChrisPasda** [comment]
Okay, i dont know what caused the problem but after restarting my VM everyhting is working now.

Thank you very much !

**Comment by kisvegabor** [comment]
Next time I suggest trying `make clean` too.
