### ISSUE TITLE
when  I  add the code in my linux systerm  and  cross compile ,   errors

### ISSUE THREAD

**Issue by justdomyself** [lvgl/lv_port_linux_frame_buffer#32]
the error code like this:

/home/alientek/Desktop/alientek/ui/lv_drivers/display/fbdev.c:175:18: error: unknown type name ‘lv_disp_drv_t’
 void fbdev_flush(lv_disp_drv_t * drv, const lv_area_t * area, lv_color_t * color_p)

**Comment by kisvegabor** [comment]
This repo is using LVGL v8, so be sure to use the `lvgl` and `lv_drivers` versions pointed by the submodules in this repo.

If you want to use lvgl `master` you just need to enable the frame buffer device in [`lv_conf.h`](https://github.com/lvgl/lvgl/blob/master/lv_conf_template.h#L759-L762) and create a display with these functions:

https://github.com/lvgl/lvgl/blob/7a9e6e08130e30e2917520c043487c5453acfb10/src/dev/disp/fb/lv_linux_fbdev.h#L32-L34

**Comment by justdomyself** [comment]
> 

thank you!  I have resove my problem。
