### ISSUE TITLE
unable to open evdev interface:: No such file or directory

### ISSUE THREAD

**Issue by suijunqiang** [lvgl/lv_port_linux_frame_buffer#37]
after ./demo throw the error "unable to open evdev interface:: No such file or directory"
I am able to make on my Raspberry Pi 4B, but unable to run ./demo

would you please give me some supports?

Thanks & Best Regards
Sui

**Comment by kisvegabor** [comment]
As it's resolved, I close this issue :slightly_smiling_face:

**Comment by xinsuinizhuan** [comment]
the same problem as you.
first, "unable to open evdev interface:: No such file or directory"
then ,change  EVDEV_NAME to be "/dev/input/event4" in lv_drv_conf.h, then no show

how do you solved this  problem?
