### ISSUE TITLE
How to implement a right-angled box through lv_obj

### ISSUE THREAD

**Issue by llechee** [lvgl/lv_port_linux_frame_buffer#49]
I need to implement a gui on my arm device LCD, but there seems to be no api to implement a rectangle, only a round box generated by lvobj_create, how do I go about it.
Another question, how can I make my program smoother and silky smooth if I run it on an embedded android device
Thanks to the developer

**Comment by kisvegabor** [comment]
> I need to implement a gui on my arm device LCD, but there seems to be no api to implement a rectangle, only a round box generated by lvobj_create, how do I go about it.

To get rid of radius you can do this:
```c
lv_obj_set_style_radius(obj, 0, LV_PART_MAIN);
```

> Another question, how can I make my program smoother and silky smooth if I run it on an embedded android device

It requires more info, like target device, display driver, display resolution, target FPS, etc. 

As it's not related to the development of LVGL, please open a topic for it in the [forum](https://forum.lvgl.io/) and post it's link here. I'll reply in the forum.
